### Numpy Task

In [2]:
import numpy as np

In [3]:
# 1~10까지의 요소를 ndarray에 담는다.
# 3행 2열 list를 ndarray에 담고 각 요소는 순서대로 6, 5, 4, 3, 2, 1이다.
# 4행 1열 ndarray, 순서대로 10, 8, 6, 4를 담는다
# 1~10까지 요소를 ndarray에 담고 각 요소에 5씩 더해준다.
# axis 0이 10인 shape이면서 모든 원소가 0, dtype은 int32인 ndarray만들기
# axis 0이 3, axis1이 4인 shape이면서 모든 원소가 1인 ndarray 만들기
# axis 0이 5, 각 요소가 0~4인 ndarray 만들기

# 아래의 ndarray1이 주어졌을 때 순서대로 문제를 해결한다.
ndarray1 = np.arange(start=0, stop=16)

# 2 Dimension, axis 1은 2로 변경
# 2 Dimension, axis 0은 8로 변경
# 3 Dimension으로 변경
# ndarray3을 axis 1이 1인 2차원 ndarray로 변환
# ndarray3을 1 Dimension으로 변환

# 1차원 ndarray 1~100까지 값 중 97값 추출하기

# 아래의 ndarray1이 주어졌을 때 순서대로 문제를 해결한다.
ndarray1 = np.arange(start=1, stop=21)

# 2차원 배열 axis 0은 4, axis 1은 5로 1~20 요소 값 중 15값 추출하기
# 2 Dimension, axis 0은 5로 변경
# 2행의 4번째 숫자 출력

# 1~100중 짝수만 출력
# 위에서 구한 짝수들을 axis 0이 10인 2차원 배열로 변환 후 82~100까지 추출
# 위에서 구한 요소 중 (86, 100) 좌표 구하기

# 아래의 ndarray1이 주어졌을 때 순서대로 문제를 해결한다.
ndarray1 = np.arange(start=1, stop=101)

# 각 요소중 1의 자리수가 2인 수들만 추출하기

# 1~49요소 중 2와 5의 공배수 추출하기
# 위에서 추출한 공배수 중 20이상인 값만 추출하기

# 데이터를 분석하여, 각 수치별 오름차순 및 내림차순 후 이름을 출력하세요.
# [[과일이름], [가격]], 가격별 내림차순
array1 = [['Mango', 'Apple', 'Pear', 'Pitch', 'Melon'], [1500, 1800, 2000, 2500, 8500]]

# [[이름], [나이], [학점]], 나이별 내림차순, 학점별 오름차순
array2 = [['둘리', '또치', '길동', '도너', '마이콜'], [7, 9, 40, 5, 20], ['C', 'A', 'B', 'F', 'D']]

# [[국가이름], [GDP 성장률]], GDP 성장률별 오름차순
array3 = [['한국', '영국', '러시아', '남아프리카 공화국', '미국'], ['1.7%', '-0.6%', '0.3%', '1.2%', '1.4%']]

In [4]:
print("○ 1번 문제")
# 1~10까지의 요소를 ndarray에 담는다.
ndarray1 = np.arange(start=1, stop=11)

print(ndarray1)

○ 1번 문제
[ 1  2  3  4  5  6  7  8  9 10]


In [5]:
print("○ 1번 문제 풀이")
ndarray1 = np.array(list(range(1, 11)))
ndarray1 = np.arange(start=1, stop=11)

print(ndarray1)

○ 1번 문제 풀이
[ 1  2  3  4  5  6  7  8  9 10]


In [153]:
print("○ 2번 문제")
# 3행 2열 list를 ndarray에 담고 각 요소는 순서대로 6, 5, 4, 3, 2, 1이다.
ndarray1 = np.arange(start=1, stop=7)
ndarray2 = ndarray1.reshape((3, -1))

print(ndarray2[::-1, ::-1])

○ 2번 문제
[[6 5]
 [4 3]
 [2 1]]


In [6]:
print("○ 2번 문제 풀이")
python_list = []
python_list.append([6 - i for i in range(2)])
python_list.append([4 - i for i in range(2)])
python_list.append([2 - i for i in range(2)])

ndarray2 = np.array(python_list)

print(type(ndarray2), ndarray2.shape, ndarray2.ndim, ndarray2.dtype, sep="\n")

○ 2번 문제 풀이
<class 'numpy.ndarray'>
(3, 2)
2
int32


In [154]:
print("○ 3번 문제")
# 4행 1열 ndarray, 순서대로 10, 8, 6, 4를 담는다
ndarray1 = np.arange(start=4, stop=11, step=2)
ndarray2 = ndarray1.reshape((4, 1))

print(ndarray2[::-1])

○ 3번 문제
[[10]
 [ 8]
 [ 6]
 [ 4]]


In [9]:
print("○ 3번 문제 풀이")
# Transpose: 전치, 행과 열을 바꿔준다.
ndarray2 = np.array([[(5 - i) * 2 for i in range(4)]]).T

print(ndarray2)

○ 3번 문제 풀이
[[10]
 [ 8]
 [ 6]
 [ 4]]


In [155]:
print("○ 4번 문제")
# 1~10까지 요소를 ndarray에 담고 각 요소에 5씩 더해준다.
ndarray1 = np.arange(start=1, stop=11)
ndarray2 =  ndarray1 + 5

print(ndarray1)
print(ndarray2)

○ 4번 문제
[ 1  2  3  4  5  6  7  8  9 10]
[ 6  7  8  9 10 11 12 13 14 15]


In [10]:
print("○ 4번 문제 풀이")
ndarray1 = np.arange(start=1, stop=11)
ndarray_oper = ndarray1 + 5

print(ndarray_oper)

○ 4번 문제 풀이
[ 6  7  8  9 10 11 12 13 14 15]


In [156]:
print("○ 5번 문제")
# axis 0이 10인 shape이면서 모든 원소가 0, dtype은 int32인 ndarray만들기
ndarray1 = np.zeros((10, ), dtype=np.int32)

print(ndarray1, ndarray1.dtype)

○ 5번 문제
[0 0 0 0 0 0 0 0 0 0] int32


In [11]:
print("○ 5번 문제 풀이")
ndarray1 = np.zeros((10,), dtype=np.int32)

print(ndarray1, ndarray1.shape, sep="\n")

○ 5번 문제 풀이
[0 0 0 0 0 0 0 0 0 0]
(10,)


In [157]:
print("○ 6번 문제")
# axis 0이 3, axis1이 4인 shape이면서 모든 원소가 1인 ndarray 만들기
ndarray1 = np.ones((3, 4))

print(ndarray1)

○ 6번 문제
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
print("○ 6번 문제 풀이")
ndarray1 = np.ones((3, 4), dtype=np.int8)

print(ndarray1, ndarray1.shape, sep="\n")

○ 6번 문제 풀이
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
(3, 4)


In [326]:
print("○ 7번 문제")
# axis 0이 5, 각 요소가 0~4인 ndarray 만들기
ndarray1 = np.arange(5)
ndarray1 = ndarray1.reshape((5, ))

print(ndarray1)

○ 7번 문제
[0 1 2 3 4]


In [13]:
print("○ 7번 문제 풀이")
ndarray1 = np.arange(stop=5)

print(ndarray1, ndarray1.shape, sep="\n")

○ 7번 문제 풀이
[0 1 2 3 4]
(5,)


In [15]:
print("○ 8번 문제")
print("· 8번 문제 1")
# 아래의 ndarray1이 주어졌을 때 순서대로 문제를 해결한다.
ndarray1 = np.arange(start=0, stop=16)

print(ndarray1)
print("\n")



print("· 8번 문제 2")
# 2 Dimension, axis 1은 2로 변경
ndarray2 = ndarray1.reshape((-1, 2))

print(ndarray2)
print(ndarray2.ndim)
print("\n")



print("· 8번 문제 3")
# 2 Dimension, axis 0은 8로 변경
ndarray2 = ndarray1.reshape((8, -1))

print(ndarray2)
print(ndarray2.ndim)
print("\n")




print("· 8번 문제 4")
# 3 Dimension으로 변경
ndarray3 = ndarray2.reshape((4, 2, -1))
print(ndarray3)
print(ndarray3.ndim)
print("\n")



print("· 8번 문제 5")
# ndarray3을 axis 1이 1인 2차원 ndarray로 변환
ndarray2 = ndarray3.reshape((-1, 1))

print(ndarray2)
print(ndarray2.ndim)
print("\n")



print("· 8번 문제 6")
# ndarray3을 1 Dimension으로 변환
ndarray1 = ndarray3.reshape((-1,))

print(ndarray1)
print(ndarray1.ndim)

○ 8번 문제
· 8번 문제 1
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


· 8번 문제 2
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
2


· 8번 문제 3
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
2


· 8번 문제 4
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]]
3


· 8번 문제 5
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]]
2


· 8번 문제 6
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
1


In [17]:
print("○ 8번 문제 풀이")
print("· 8번 문제 1 풀이")
# 아래의 ndarray1이 주어졌을 때 순서대로 문제를 해결한다.
ndarray1 = np.arange(start=0, stop=16)

print(ndarray1)
print("\n")



print("· 8번 문제 2 풀이")
# 2 Dimension, axis 1은 2로 변경
ndarray2 = ndarray1.reshape((-1, 2))

print(ndarray2, ndarray2.shape, sep="\n")
print("\n")



print("· 8번 문제 3 풀이")
# 2 Dimension, axis 0은 8로 변경
ndarray2 = ndarray1.reshape((8, -1))

print(ndarray2, ndarray2.shape, sep="\n")
print("\n")




print("· 8번 문제 4 풀이")
# 3 Dimension으로 변경
ndarray3 = ndarray2.reshape((4, 2, -1))

print(ndarray3, ndarray3.shape, sep="\n")
print("\n")



print("· 8번 문제 5 풀이")
# ndarray3을 axis 1이 1인 2차원 ndarray로 변환
ndarray2 = ndarray3.reshape((-1, 1))

print(ndarray2, ndarray2.shape, sep="\n")
print("\n")



print("· 8번 문제 6 풀이")
# ndarray3을 1 Dimension으로 변환
#ndarray1 = ndarray3.reshape((-1,))

# flatten 시 1차원으로 바꿔준다.
ndarray1 = ndarray3.flatten()

print(ndarray1, ndarray1.shape, sep="\n")

○ 8번 문제 풀이
· 8번 문제 1 풀이
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


· 8번 문제 2 풀이
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
(8, 2)


· 8번 문제 3 풀이
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
(8, 2)


· 8번 문제 4 풀이
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]]
(4, 2, 2)


· 8번 문제 5 풀이
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]]
(16, 1)


· 8번 문제 6 풀이
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
(16,)


In [226]:
print("○ 9번 문제")
# 1차원 ndarray 1~100까지 값 중 97값 추출하기
ndarray1 = np.arange(1, 101)

print(ndarray1[-4])

○ 9번 문제
97


In [18]:
print("○ 9번 문제 풀이")
ndarray1 = np.arange(start=1, stop=101)

print(ndarray1[96])

○ 9번 문제 풀이
97


In [227]:
print("○ 10번 문제")
# 아래의 ndarray1이 주어졌을 때 순서대로 문제를 해결한다.
ndarray1 = np.arange(start=1, stop=21)

print(ndarray1)
print("\n")



print("· 10번 문제 1")
# 2차원 배열 axis 0은 4, axis 1은 5로 1~20 요소 값 중 15값 추출하기
ndarray2 = ndarray1.reshape(4, 5)

print(ndarray2[2, 4])
print("\n")



print("· 10번 문제 2")
# 2 Dimension, axis 0은 5로 변경
ndarray2 = ndarray2.reshape((5, -1))

print(ndarray2)
print("\n")



print("· 10번 문제 3")
# 2행의 4번째 숫자 출력
print(ndarray2[1, 3])

○ 10번 문제
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


· 10번 문제 1
15


· 10번 문제 2
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


· 10번 문제 3
8


In [20]:
print("○ 10번 문제 풀이")
# 아래의 ndarray1이 주어졌을 때 순서대로 문제를 해결한다.
ndarray1 = np.arange(start=1, stop=21)

print(ndarray1)
print("\n")



print("· 10번 문제 1 풀이")
# 2차원 배열 axis 0은 4, axis 1은 5로 1~20 요소 값 중 15값 추출하기
ndarray2 = ndarray1.reshape((4, 5))

print(ndarray2[2, 4])
print("\n")



print("· 10번 문제 2 풀이")
# 2 Dimension, axis 0은 5로 변경
ndarray2 = ndarray2.reshape((5, -1))

print(ndarray2)
print("\n")



print("· 10번 문제 3 풀이")
# 2행의 4번째 숫자 출력
print(ndarray2[1, 3])

○ 10번 문제 풀이
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


· 10번 문제 1 풀이
15


· 10번 문제 2 풀이
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


· 10번 문제 3 풀이
8


In [343]:
print("○ 11번 문제")
print("· 11번 문제 1-1")
# 1~100중 짝수만 출력
ndarray1 = np.arange(start=1, stop=101)

print(ndarray1[ndarray1 % 2 == 0])
print("\n")

print("· 11번 문제 1-2")
ndarray1 = np.arange(start=2, stop=101, step=2)

print(ndarray1)
print("\n")



print("· 11번 문제 2")
# 위에서 구한 짝수들을 axis 0이 10인 2차원 배열로 변환 후 82~100까지 추출
ndarray2 = ndarray1.reshape(10, -1)

print(ndarray2[-2:])
print("\n")



print("· 11번 문제 3")
# 위에서 구한 요소 중 (86, 100) 좌표 구하기
print(np.where(ndarray2[-2:] == 86))
print(np.where(ndarray2[-2:] == 100))

○ 11번 문제
· 11번 문제 1-1
[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


· 11번 문제 1-2
[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


· 11번 문제 2
[[ 82  84  86  88  90]
 [ 92  94  96  98 100]]


· 11번 문제 3
(array([0], dtype=int64), array([2], dtype=int64))
(array([1], dtype=int64), array([4], dtype=int64))


In [27]:
print("○ 11번 문제 풀이")
print("· 11번 문제 1 풀이")
# 1~100중 짝수만 출력
ndarray1 = np.arange(start=1, stop=101)
ndarray1_even = ndarray1[ndarray1 % 2 == 0]

print(ndarray1_even)
print("\n")



print("· 11번 문제 2 풀이")
# 위에서 구한 짝수들을 axis 0이 10인 2차원 배열로 변환 후 82~100까지 추출
ndarray2_even = ndarray1_even.reshape((10, -1))

print(ndarray2_even[8:].flatten())
print("\n")



print("· 11번 문제 3 풀이")
# 위에서 구한 요소 중 (86, 100) 좌표 구하기
ndarray2_even_ex = ndarray2_even[8:]

print(ndarray2_even_ex)

print("86의 좌표(x,y): (0, 2)")
print("100의 좌표(x,y): (1, 4)")
print(ndarray2_even_ex[0, 2], ndarray2_even_ex[1,4])

○ 11번 문제 풀이
· 11번 문제 1 풀이
[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


· 11번 문제 2 풀이
[ 82  84  86  88  90  92  94  96  98 100]


· 11번 문제 3 풀이
[[ 82  84  86  88  90]
 [ 92  94  96  98 100]]
86의 좌표(x,y): (0, 2)
100의 좌표(x,y): (1, 4)
86 100


In [26]:
print("○ 12번 문제")
# 아래의 ndarray1이 주어졌을 때 순서대로 문제를 해결한다.
ndarray1 = np.arange(start=1, stop=101)

print(ndarray1)
print("\n")



print("· 12번 문제 1")
# 각 요소중 1의 자리수가 2인 수들만 추출하기
print(ndarray1[ndarray1 % 10 == 2])
print("\n")



print("· 12번 문제 2")
# 1~49요소 중 2와 5의 공배수 추출하기
ndarray1 = ndarray1[:49]
ndarray1 = ndarray1[(ndarray1 % 2 == 0) & (ndarray1 % 5 == 0)]

print(ndarray1)
print("\n")



print("· 12번 문제 3")
# 위에서 추출한 공배수 중 20이상인 값만 추출하기
print(ndarray1[ndarray1 >= 20])

○ 12번 문제
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


· 12번 문제 1
[ 2 12 22 32 42 52 62 72 82 92]


· 12번 문제 2
[10 20 30 40]


· 12번 문제 3
[20 30 40]


In [29]:
print("○ 12번 문제 풀이")
# 아래의 ndarray1이 주어졌을 때 순서대로 문제를 해결한다.
ndarray1 = np.arange(start=1, stop=101)

print(ndarray1)
print("\n")



print("· 12번 문제 1 풀이")
# 각 요소중 1의 자리수가 2인 수들만 추출하기
print(ndarray1[ndarray1 % 10 == 2])
print("\n")



print("· 12번 문제 2 풀이")
# 1~49요소 중 2와 5의 공배수 추출하기
ndarray1 = np.arange(start=1, stop=50)
condition1 = ndarray1 % 2 == 0
condition2 = ndarray1 % 5 == 0
condition3 = condition1 & condition2
result = ndarray1[condition3]

print(result)
print("\n")



print("· 12번 문제 3 풀이")
# 위에서 추출한 공배수 중 20이상인 값만 추출하기
condition = result >= 20
print(result[condition])

○ 12번 문제 풀이
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


· 12번 문제 1 풀이
[ 2 12 22 32 42 52 62 72 82 92]


· 12번 문제 2 풀이
[10 20 30 40]


· 12번 문제 3 풀이
[20 30 40]


In [30]:
print("○ 13번 문제")
# 데이터를 분석하여, 각 수치별 오름차순 및 내림차순 후 이름을 출력하세요.
# [[과일이름], [가격]], 가격별 내림차순
array1 = [['Mango', 'Apple', 'Pear', 'Pitch', 'Melon'], [1500, 1800, 2000, 2500, 8500]]

name = np.array(array1[0])
price = np.array(array1[1])



print("· 13번 문제 1")
# 오름차순
print(name.argsort())
print(price.argsort())
print("\n")



print("· 13번 문제 2")
# 내림차순
print(name.argsort()[::-1])
print(price.argsort()[::-1])
print("\n")



print("· 13번 문제 3")
print(name[price.argsort()][::-1])

○ 13번 문제
· 13번 문제 1
[1 0 4 2 3]
[0 1 2 3 4]


· 13번 문제 2
[3 2 4 0 1]
[4 3 2 1 0]


· 13번 문제 3
['Melon' 'Pitch' 'Pear' 'Apple' 'Mango']


In [32]:
print("○ 13번 문제 풀이")
# 데이터를 분석하여, 각 수치별 오름차순 및 내림차순 후 이름을 출력하세요.
# [[과일이름], [가격]], 가격별 내림차순
array1 = [['Mango', 'Apple', 'Pear', 'Pitch', 'Melon'], [1500, 1800, 2000, 2500, 8500]]

ndarray2 = np.array(array1)
fruit_name = ndarray2[:1].flatten()
fruit_price = ndarray2[-1]

print(fruit_name, fruit_price, sep="\n")

fruit_name_asc = fruit_name[fruit_price.argsort()[::-1]]
print(fruit_name_asc)

○ 13번 문제 풀이
['Mango' 'Apple' 'Pear' 'Pitch' 'Melon']
['1500' '1800' '2000' '2500' '8500']
['Melon' 'Pitch' 'Pear' 'Apple' 'Mango']


In [330]:
print("○ 14번 문제")
# [[이름], [나이], [학점]], 나이별 내림차순, 학점별 오름차순
array2 = [['둘리', '또치', '길동', '도너', '마이콜'], [7, 9, 40, 5, 20], ['C', 'A', 'B', 'F', 'D']]

name= np.array(array2[0])
age = np.array(array2[1])
grade = np.array(array2[2])


print("· 14번 문제 1")
# 나이별 내림차순
print(name[age.argsort()][::-1])
print("\n")



print("· 14번 문제 2")
# 학점별 오름차순
print(name[grade.argsort()])

○ 14번 문제
· 14번 문제 1
['길동' '마이콜' '또치' '둘리' '도너']


· 14번 문제 2
['또치' '길동' '둘리' '마이콜' '도너']


In [38]:
print("○ 14번 문제 풀이")
# [[이름], [나이], [학점]], 나이별 내림차순, 학점별 오름차순
array2 = [['둘리', '또치', '길동', '도너', '마이콜'], [7, 9, 40, 5, 20], ['C', 'A', 'B', 'F', 'D']]

ndarray2 = np.array(array2)
names = ndarray2[:1].flatten()
ages = ndarray2[1].astype(np.int16)
grades = ndarray2[-1]

print(names.dtype, ages.dtype, grades.dtype)

print(names[ages.argsort()[::-1]])
print(names[grades.argsort()])

○ 14번 문제 풀이
<U11 int16 <U11
['길동' '마이콜' '또치' '둘리' '도너']
['또치' '길동' '둘리' '마이콜' '도너']


In [332]:
print("○ 15번 문제")
# [[국가이름], [GDP 성장률]], GDP 성장률별 오름차순
array3 = [['한국', '영국', '러시아', '남아프리카 공화국', '미국'], ['1.7%', '-0.6%', '0.3%', '1.2%', '1.4%']]

name = np.array(array3[0])
gdp = np.array(array3[1])

print(name[gdp.argsort()])

○ 15번 문제
['영국' '러시아' '남아프리카 공화국' '미국' '한국']


In [45]:
print("○ 15번 문제 풀이")
# [[국가이름], [GDP 성장률]], GDP 성장률별 오름차순
array3 = [['한국', '영국', '러시아', '남아프리카 공화국', '미국'], ['1.7%', '-0.6%', '0.3%', '1.2%', '1.4%']]
gdp_list = []

ndarray2 = np.array(array3)

nations = ndarray2[0]
gdps = ndarray2[1]

for gdp in gdps:
    gdp_list.append(gdp.replace('%', ''))

gdps = np.array(gdp_list, dtype=np.float16)

print(nations[gdps.argsort()])

○ 15번 문제 풀이
['영국' '러시아' '남아프리카 공화국' '미국' '한국']
